#!/bin/bash -x

# Copyright (C) 2022 ScotDex <themadlyscientific@gmail.com>

# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved. 

# Remember when running an update you have the option to sudo apt-mark hold <package name> which prevents whatever named package being upgraded.

# Also note these scripts are strictly for command line based op, there are additional commands to clear space for the desktop versions.

# Based on the ubuntu distribution

########################

sudo apt-get update # This lists off the available updates 
sudo apt-get upgrade # This kicks off updating all packages to the latest versions

#######################
